apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 2Gi
